# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, test_master]
  pull_request:
name: R-CMD-check.yaml
permissions: read-all
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          
      # Set up Python to resolve the python3 dependency
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      # Install necessary checking packages directly
      - name: Install packages for checking
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c("rcmdcheck", "sessioninfo", "remotes"))
        shell: Rscript {0}
      
      # Install individual dependencies instead of using remotes::install_deps
      - name: Install individual package dependencies
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          # List all required packages individually
          pkgs <- c(
            "data.table", "doParallel", "exactextractr", "foreach", 
            "geodata", "haven", "httr", "jsonlite", "lubridate", 
            "lwgeom", "memoise", "methods", "ncdf4", "osmdata", 
            "parallel", "parallelMap", "progress", "R.utils", "raster", 
            "reticulate", "rstac", "rvest", "sf", "stringr", "terra", 
            "tools", "units", "testthat", "crsuggest", "dbscan"
          )
          install.packages(pkgs, dependencies = TRUE)
        shell: Rscript {0}
        
      # Run R CMD check
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
